export const SidebarData = [
  {
    title: "Preferences",
    path: "eRADWeb/preferences",
    cName: "sidenav nav-link text-secondary text-left",
    id: "preferences",
    parentId: "preferences",
    disabled: true,
  },
  {
    title: "Bond & RAD / RAC Types",
    path: "eRADWeb/deductiontype",
    cName: "sidenav nav-link text-secondary text-left",
    id: "deduction",
    parentId: "preferences",
    disabled: true,
  },
  {
    title: "Transferred Facilities",
    path: "eRADWeb/transferredfacilities",
    cName: "sidenav nav-link text-secondary text-left",
    id: "transferredfacilities",
    parentId: "preferences",
    disabled: true,
  },
  {
    title: "Representative Categories",
    path: "eRADWeb/representativecategory",
    cName: "sidenav nav-link text-secondary text-left",
    id: "representativecategory",
    parentId: "preferences",
    disabled: true,
  },
  {
    title: "Additional Services",
    path: "eRADWeb/additionalservices",
    cName: "sidenav nav-link text-secondary text-left",
    id: "additionalservices",
    parentId: "preferences",
    disabled: true,
  },
  {
    title: "Document Types",
    path: "eRADWeb/documenttypes",
    cName: "sidenav nav-link text-secondary text-left",
    id: "document",
    parentId: "preferences",
    disabled: true,
  },
  {
    title: "Resident Letters",
    path: "eRADWeb/residentletter",
    cName: "sidenav nav-link text-secondary text-left",
    parentId: "residentlettters",
    id: "residentletter",
    disabled: true,
  },

  {
    title: "Fees & Charges",
    path: "eRADWeb/feeAndCharges",
    cName: "sidenav nav-link text-secondary text-left",
    parentId: "feeCharges",
    id: "feeAndCharges",
    disabled: true,
  },
  {
    title: "Tags Directory",
    path: "eRADWeb/tagsDirectory",
    cName: "sidenav nav-link text-secondary text-left",
    parentId: "residentlettters",
    id: "tagsDirectory",
    disabled: true,
  },

  {
    title: "Notes and Links",
    path: "eRADWeb/notesandlinks",
    cName: "sidenav nav-link text-secondary text-left",
    parentId: "prudentialreq",
    id: "notesandlinks",
    disabled: true,
  },
  {
    title: "Prudential Requirements",
    path: "eRADWeb/prudentialtabs",
    cName: "sidenav nav-link text-secondary text-left",
    parentId: "prudentialreq",
    id: "prudentialtabs",
    disabled: true,
  },
  {
    title: "addResident",
    path: "eRADWeb/addResident",
    cName: "sidenav nav-link text-secondary text-left",
    id: "addResident",
    parentId: "register",
    disabled: true,
  },
];
