export const TopHeaderData = [
  {
    title: "Register",
    path: "eRADWeb/viewResident",
    id: "register",
    cName: "topdata nav-item nav-link text-white",
    disabled: false,
    hasSideMenu: false,
    isHavingSubMenues: false,
    showSameActive: "register",
  },
  {
    title: "End of Period",
    path: "eRADWeb/endOfPeriod",
    id: "eop",
    cName: "topdata nav-item nav-link text-white",
    disabled: false,
    hasSideMenu: false,
    isHavingSubMenues: false,
  },
  {
    title: "Overview",
    path: "/",
    id: "overview",
    cName: "topdata nav-item nav-link text-white disabled",
    disabled: true,
    hasSideMenu: false,
    isHavingSubMenues: false,
  },
  {
    title: "Prudential Req",
    path: "eRADWeb/notesandlinks",
    id: "prudentialreq",
    cName: "topdata nav-item nav-link text-white ",
    disabled: false,
    hasSideMenu: "prudentialreq",
    isHavingSubMenues: false,
  },
  {
    title: "Reports",
    path: "eRADWeb/reports",
    id: "reports",
    cName: "topdata nav-item nav-link text-white ",
    disabled: false,
    hasSideMenu: false,
    isHavingSubMenues: false,
  },
  {
    title: "Settings",
    path: "/",
    id: "Settings",
    cName: "topdata nav-item nav-link text-white ",
    disabled: false,
    screenName: "MainLayout",
    hasSideMenu: false,
    isHavingSubMenues: true,
    isHidden: true,
  },
  {
    title: "Facility",
    path: "eRADWeb/facility",
    id: "facility",
    cName: "topdata nav-item nav-link text-white ",
    disabled: false,
    screenName: "facility",
    hasSideMenu: false,
    isHavingSubMenues: false,
    isHidden: true,
  },
];
